version: '3.8'
services:
  app:
    build:
      context: .
      target: production
      dockerfile: Dockerfile
    container_name: metanews
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"
